spring:
  data:
    mongodb:
      username: root
      password: example
      host: mongo
      database: customer
      authentication-database: admin
      port: 27017
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:org.hamlet.ecommerce.payload.request.OrderConfirmationRequest,paymentNotification:org.hamlet.ecommerce.payload.request.PaymentNotificationRequest

  mail:
    host: localhost
    port: 1025
    username: hamlet
    password: 1234
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040
